// Generated by CoffeeScript 1.3.1
(function() {
  'use strict';

  var MAIN_FRAME_SELECTOR, inbox, linkCSS, payment;

  console.log('Value for Gmail extension script loaded');

  window.addEventListener('hashchange', function() {
    if (window.location.hash.match(/compose/)) {
      return payment.renderButton();
    }
  });

  MAIN_FRAME_SELECTOR = '#canvas_frame';

  linkCSS = function($frame) {
    return $frame.contents().find('head').append($('<link/>', {
      rel: 'stylesheet',
      type: 'text/css',
      href: chrome.extension.getURL('gmail_canvas.css')
    }));
  };

  payment = {
    renderButton: function() {
      var $actions, $frame;
      $frame = $(MAIN_FRAME_SELECTOR);
      linkCSS($frame);
      $actions = $frame.contents().find('div[role=navigation]').last().children().first();
      $actions.children('span').remove();
      return $actions.children().last().before('<div id="payment-button">$<input type="text" name="pay_amount" /></div>');
    }
  };

  inbox = {
    sort: function() {
      var $emails, emails;
      $emails = $(MAIN_FRAME_SELECTOR).contents().find('table > colgroup').eq(1).parent().find('tr');
      emails = _(emails).map(function(email, i) {
        var subject, value;
        subject = email.find('td[role=link] div > span:first-child').text();
        value = subject.match(/^\$[+-]?[0-9]{1,3}(?:,?[0-9]{3})*(?:\.[0-9]{2})?\$/);
        if (value != null) {
          value = parseFloat(value[0][{
            1: -2
          }]);
        } else {
          value = 0;
        }
        return {
          subject: subject,
          value: value,
          index: i
        };
      });
      return console.log(emails);
    }
  };

  $(MAIN_FRAME_SELECTOR).load(function() {
    console.log('main frame loaded');
    if (window.location.hash.match(/inbox/)) {
      return inbox.sort();
    } else if (window.location.hash.match(/compose/)) {
      return payment.renderButton();
    }
  });

  $(function() {});

}).call(this);
