// Generated by CoffeeScript 1.3.1
(function() {
  var currVersion, getVersion, onInstall, onUpdate, prevVersion;

  onInstall = function() {
    alert("Extension Installed");
    return null;
  };

  onUpdate = function() {
    alert("Extension Updated");
    return null;
  };

  getVersion = function() {
    var details;
    details = chrome.app.getDetails();
    return details.version;
  };

  currVersion = getVersion();

  prevVersion = localStorage['version'];

  if (currVersion !== prevVersion) {
    if (typeof prevVersion === 'undefined') {
      onInstall();
    } else {
      onUpdate();
    }
    localStorage['version'] = currVersion;
  }

}).call(this);
