// Generated by CoffeeScript 1.3.3
(function() {
  var currVersion, getVersion, onInstall, onUpdate, prevVersion;

  onInstall = function() {
    localStorage['needsHelp'] = true;
    chrome.tabs.getSelected(function(tab) {
      return chrome.tabs.update(tab.id, {
        'url': "http://mail.google.com"
      });
    });
    return null;
  };

  onUpdate = function() {
    alert("Extension Updated");
    return null;
  };

  getVersion = function() {
    var details;
    details = chrome.app.getDetails();
    return details.version;
  };

  currVersion = getVersion();

  prevVersion = localStorage['version'];

  if (currVersion !== prevVersion) {
    if (typeof prevVersion === 'undefined') {
      onInstall();
    } else {
      onUpdate();
    }
    localStorage['version'] = currVersion;
  }

  chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    if (request.method === "getLocalStorage") {
      return sendResponse({
        data: localStorage[request.key]
      });
    } else if (request.method === "setLocalStorage") {
      localStorage[request.key] = request.value;
      return sendResponse({
        data: localStorage[request.key]
      });
    } else {
      return sendResponse({});
    }
  });

}).call(this);
