"""Add card and bank information

Revision ID: 46181739f11a
Revises: 789c82713d9
Create Date: 2012-09-16 08:56:15.608683

"""

# revision identifiers, used by Alembic.
revision = '46181739f11a'
down_revision = '789c82713d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('card_uri', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('bank_account_uri', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bank_account_uri')
    op.drop_column('user', 'card_uri')
    ### end Alembic commands ###
