"""Add openid

Revision ID: 6204b5143f0
Revises: 52b8d5765c69
Create Date: 2012-09-15 05:39:46.922671

"""

# revision identifiers, used by Alembic.
revision = '6204b5143f0'
down_revision = '52b8d5765c69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('openid', sa.String(length=255), nullable=False))
    op.alter_column('user', u'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', u'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', u'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', u'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'openid')
    ### end Alembic commands ###
