"""Added user email

Revision ID: 789c82713d9
Revises: 6204b5143f0
Create Date: 2012-09-15 15:38:41.120575

"""

# revision identifiers, used by Alembic.
revision = '789c82713d9'
down_revision = '6204b5143f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###
